apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace

  tasks:
    - name: npm-install
      taskRef:
        name: npm
      workspaces:
        - name: shared-workspace

    - name: tests
      runAfter:
        - npm-install
      taskRef:
        name: jasmine
      workspaces:
        - name: shared-workspace

    - name: build
      runAfter:
        - tests
      taskSpec:
        workspaces:
          - name: shared-workspace
        steps:
          - name: build
            image: node:18
            workingDir: $(workspaces.shared-workspace.path)
            script: |
              #!/usr/bin/env sh
              npm run build
